apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-backend
  template:
    metadata:
      labels:
        app: ecom-backend
    spec:
      containers:
      - name: ecom-backend
        image: rudrasankha/ecom-app-test:1
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: env-file
          readOnly: true
          mountPath: "/app/"
      volumes:
      - name: env-file
        secret:
          secretName: backend-secret