version: '3.8'

services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - monitoring
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

networks:
  monitoring:
    driver: bridge